# MyBatis ?? ??
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.jy.domain

# ?????? ??
spring.datasource.url=jdbc:mysql://localhost:3306/side_project_schema?serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=ahd190611!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
